### 查询服务实例信息
GET http://127.0.0.1:8000/ecommerce-nacos-client/nacos-client/service-instance
Accept: application/json

### 动态从 Nacos Server 中获取配置信息
GET http://127.0.0.1:8000/ecommerce-nacos-client/nacos-client/project-config
Accept: application/json

### 查看 Sleuth 跟踪信息
GET http://127.0.0.1:9001/imooc/ecommerce-nacos-client/sleuth/trace-info
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcIkltb29jUWlueWlAaW1vb2MuY29tXCJ9IiwianRpIjoiZmVkNTI5ZmEtMTZlMS00MDBkLTk1YzctMTFmNzg4NjM5MzRmIiwiZXhwIjoxNjMyNDEyODAwfQ.ZeY4rcJZUwvcaGambVLkvFhT2u-KUCwUHOg2Qr7gavGlxxEsDakWH_sIoCWaxOEkJ9nihAl3xQOKkhpDdLfrVbkwrG5hR2aZVNSEnola9bzIhR06T-b8N4PjG9Ale1nHmIraMqj_SuGnf4n24LXi42KcYKWKq933AnPXupuldZ8tRL7v78tixT88Xtw1QzFHgeOTl-OleK5OqjzccTtp3PnBAqTg62gYjHb6B5WTQ0qId_t2aysboekIOqPYXmSMGz2sBCQcc_oN8vRM-zyuWr1lmfa0VvQRJ-zqh_xDQGrUhNfw6dKyX03rMt_RT5RU1otPDcsYSftvTos389bjDg
token: imooc
