### 查询服务
GET http://127.0.0.1:9001/imooc/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcIkltb29jUWlueWlAaW1vb2MuY29tXCJ9IiwianRpIjoiZDFlMzg5MjctMjM0OC00MWQ0LWEwZTgtNzQ1MDMyOTI1NWZmIiwiZXhwIjoxNjMyMzI2NDAwfQ.Ci2f6Mk0QOHZMpC5HW2WaQoEYRYR9sJx7kfdD0ePmKlg0Dbh4WdF3ueN_ptAY7Ik6QYBLKlvX5NJA-VJxgVWfCOgAe85jhGcSGqmkaLCmjHwmJsGD404RTq-tHxAcWuukEAFozaKIr9yBcx-X2XAdTvsOJUxcxx8OgPSu7F_Pv__IdRG4oLCnhukmeQT70pNDcxPY1h8Nu8S00iWv9cM5Yi_ZUfpkIql8WsTk_W_qPGW15onvEq_pD-QLq_4w_Ukv7ggu8ssBF22yajwi9CdE2UWLK9_6l7vIU_aL1EmrndWrpbBRg9pSM16mm_aEAtayE5aTeIqJ5XGQzj9MoQi4g
token: imooc
